### ISSUE TITLE
Reset Button

### ISSUE THREAD

**Issue by Gehstock** [boert/Z1013-mist#1]
This will activate the Right Button on Mist for Reset

>     ------------------------------------
>     -- reset generator
>     --
>     process
>     begin
>         wait until rising_edge( cpu_clk);
> 
>         if reset_counter > 0 then
>             reset_counter   <= reset_counter - 1;
>         else
>             sys_reset       <= '0';
>         end if;
> 
>         -- all reset sources:
>         if  ( user_io_status(0)='1')--ARM Reset
> 				or ( user_io_status(1)='1')--Menu Reset
> 				or ( user_io_buttons(1)='1')--Right Button on Mist
>             or ( pll_locked = '0') 
>             or ( data_io_inst_download = '1' and unsigned( data_io_index) = 0)
>         then
>             reset_counter   <= 255;
>             sys_reset       <= '1';
>         end if;
> 
>     end process;
>     sys_reset_n <= not sys_reset;

and add this to user_io
` buttons			=> user_io_buttons,     -- : out std_logic_vector( 1 downto 0);`

Contact me here:http://www.atari-forum.com/memberlist.php?mode=viewprofile&u=25549 ich bin aus Görlitz

**Comment by boert** [comment]
Included your suggestion in the latest commit, thanks!
